<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/config.php';
app_boot();
function review_media_exists(int $mediaId): array { $uid=current_user_id(); $st=db()->prepare('SELECT id,type,title FROM media WHERE id=? AND type IN (\'audio\',\'video\') AND ((origin=\'official\' AND is_published=1) OR (origin=\'user\' AND user_id=?)) LIMIT 1'); $st->execute([$mediaId,$uid]); $m=$st->fetch(); if(!$m)json_response(false,'Media item not found or not available.',null,404); return $m; }
$action=$_GET['action']??$_POST['action']??'';
if($action==='summary_batch'){
 $raw=trim((string)($_GET['media_ids']??''));$ids=array_values(array_unique(array_filter(array_map('intval',explode(',',$raw)),fn($v)=>$v>0)));if(!$ids)json_response(true,'Rating summaries',[]);if(count($ids)>60)$ids=array_slice($ids,0,60);$pdo=db();$ph=implode(',',array_fill(0,count($ids),'?'));$st=$pdo->prepare("SELECT r.media_id,ROUND(AVG(r.rating),1) average,COUNT(*) count,COALESCE(rv.review_count,0) review_count FROM ratings r LEFT JOIN (SELECT media_id,COUNT(*) review_count FROM reviews WHERE media_id IN ($ph) GROUP BY media_id) rv ON rv.media_id=r.media_id WHERE r.media_id IN ($ph) GROUP BY r.media_id,rv.review_count");$st->execute([...$ids,...$ids]);$out=[];foreach($st->fetchAll() as $r)$out[(string)$r['media_id']] = ['average'=>(float)$r['average'],'count'=>(int)$r['count'],'review_count'=>(int)$r['review_count']];foreach($ids as $id){$k=(string)$id;if(!isset($out[$k]))$out[$k]=['average'=>0,'count'=>0,'review_count'=>0];}json_response(true,'Rating summaries',$out);
}
if($action==='summary'){
 $mediaId=(int)($_GET['media_id']??0);if($mediaId<1)json_response(false,'Invalid media id.',null,422);review_media_exists($mediaId);$pdo=db();
 $st=$pdo->prepare('SELECT COALESCE(AVG(rating),0) avg_rating,COUNT(*) rating_count FROM ratings WHERE media_id=?');$st->execute([$mediaId]);$rating=$st->fetch();
 $dist=$pdo->prepare('SELECT rating,COUNT(*) count FROM ratings WHERE media_id=? GROUP BY rating');$dist->execute([$mediaId]);$distribution=['1'=>0,'2'=>0,'3'=>0,'4'=>0,'5'=>0];foreach($dist->fetchAll() as $r)$distribution[(string)$r['rating']] = (int)$r['count'];
 $sort=$_GET['sort']??'newest';$order=$sort==='oldest'?'r.created_at ASC':($sort==='helpful'?'COALESCE(h.helpful_count,0) DESC, r.created_at DESC':'r.created_at DESC');$limit=max(1,min(50,(int)($_GET['limit']??10)));
 $countSt=$pdo->prepare('SELECT COUNT(*) FROM reviews WHERE media_id=?');$countSt->execute([$mediaId]);$reviewCount=(int)$countSt->fetchColumn();
 $reviews=$pdo->prepare("SELECT r.id,r.user_id,r.body,r.created_at,r.updated_at,u.name AS user_name,COALESCE(h.helpful_count,0) helpful_count,CASE WHEN vh.review_id IS NULL THEN 0 ELSE 1 END viewer_helpful FROM reviews r INNER JOIN users u ON u.id=r.user_id LEFT JOIN (SELECT review_id,COUNT(*) helpful_count FROM review_helpful GROUP BY review_id) h ON h.review_id=r.id LEFT JOIN review_helpful vh ON vh.review_id=r.id AND vh.user_id=? WHERE r.media_id=? ORDER BY $order LIMIT $limit");$mineUser=current_user_id();$reviews->execute([$mineUser?:0,$mediaId]);
 $mineUser=current_user_id();$myRating=null;$myReview=null;if($mineUser){$q=$pdo->prepare('SELECT rating FROM ratings WHERE user_id=? AND media_id=?');$q->execute([$mineUser,$mediaId]);$myRating=$q->fetchColumn();$q=$pdo->prepare('SELECT id,body,created_at,updated_at FROM reviews WHERE user_id=? AND media_id=?');$q->execute([$mineUser,$mediaId]);$myReview=$q->fetch()?:null;}
 json_response(true,'Review summary',['average'=>round((float)$rating['avg_rating'],1),'count'=>(int)$rating['rating_count'],'review_count'=>$reviewCount,'distribution'=>$distribution,'myRating'=>$myRating!==false&&$myRating!==null?(int)$myRating:null,'myReview'=>$myReview,'reviews'=>$reviews->fetchAll(),'has_more'=>$limit<$reviewCount]);
}
if($action==='rate'){
 require_auth();require_method('POST');require_csrf('public_csrf');$d=request_json();$mediaId=(int)($d['mediaId']??0);$rating=(int)($d['rating']??0);if($mediaId<1||$rating<1||$rating>5)json_response(false,'Rating must be between 1 and 5.',null,422);review_media_exists($mediaId);$uid=require_auth();db()->prepare('INSERT INTO ratings(user_id,media_id,rating) VALUES(?,?,?) ON DUPLICATE KEY UPDATE rating=VALUES(rating),updated_at=CURRENT_TIMESTAMP')->execute([$uid,$mediaId,$rating]);db()->prepare('INSERT INTO analytics_events(event_type,user_id,media_id,value) VALUES(\'rating\',?,?,?)')->execute([$uid,$mediaId,$rating]);json_response(true,'Rating saved.',['rating'=>$rating]);
}
if($action==='review'){
 $uid=require_auth();require_method('POST');require_csrf('public_csrf');$d=request_json();$mediaId=(int)($d['mediaId']??0);$body=trim((string)($d['body']??''));if($mediaId<1||$body==='')json_response(false,'Review text is required.',null,422);if(mb_strlen($body)>2000)json_response(false,'Review is too long.',null,422);review_media_exists($mediaId);$pdo=db();$st=$pdo->prepare('INSERT INTO reviews(user_id,media_id,body) VALUES(?,?,?) ON DUPLICATE KEY UPDATE body=VALUES(body),updated_at=CURRENT_TIMESTAMP');$st->execute([$uid,$mediaId,$body]);json_response(true,'Review saved.');
}
if($action==='delete_review'){
 $uid=require_auth();require_method('POST');require_csrf('public_csrf');$d=request_json();$id=(int)($d['id']??0);if($id<1)json_response(false,'Invalid review.',null,422);$st=db()->prepare('DELETE FROM reviews WHERE id=? AND user_id=?');$st->execute([$id,$uid]);if($st->rowCount()===0)json_response(false,'Review not found.',null,404);json_response(true,'Review removed.');
}
if($action==='helpful'){
 $uid=require_auth();require_method('POST');require_csrf('public_csrf');$d=request_json();$reviewId=(int)($d['review_id']??0);if($reviewId<1)json_response(false,'Invalid review.',null,422);$st=db()->prepare('SELECT id FROM reviews WHERE id=? LIMIT 1');$st->execute([$reviewId]);if(!$st->fetch())json_response(false,'Review not found.',null,404);$pdo=db();$q=$pdo->prepare('SELECT 1 FROM review_helpful WHERE review_id=? AND user_id=?');$q->execute([$reviewId,$uid]);if($q->fetch()){ $pdo->prepare('DELETE FROM review_helpful WHERE review_id=? AND user_id=?')->execute([$reviewId,$uid]);$helpful=false;}else{$pdo->prepare('INSERT INTO review_helpful(review_id,user_id) VALUES(?,?)')->execute([$reviewId,$uid]);$helpful=true;}$c=$pdo->prepare('SELECT COUNT(*) FROM review_helpful WHERE review_id=?');$c->execute([$reviewId]);json_response(true,$helpful?'Marked helpful':'Removed helpful mark',['helpful'=>$helpful,'helpful_count'=>(int)$c->fetchColumn()]);
}
json_response(false,'Unknown review action.',null,400);
