<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/guard.php';
$user=require_admin_page();$csrf=csrf_token('admin_csrf');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SOUNDGROUP — Playlist Management</title><link rel="stylesheet" href="assets/admin.css"></head>
<body class="admin-body"><div class="admin-app" data-admin-user-id="<?= (int)$user['id'] ?>" data-admin-csrf="<?= htmlspecialchars($csrf,ENT_QUOTES,'UTF-8') ?>">
<aside class="admin-sidebar" id="admin-sidebar"><div class="admin-sidebar-top"><a href="index.php" class="admin-brand"><span class="admin-brand-mark">◈</span><span>SOUNDGROUP</span><em>ADMIN</em></a><button class="admin-icon-btn admin-mobile-close" id="admin-sidebar-close" aria-label="Close navigation">×</button></div>
<nav class="admin-nav" aria-label="Admin navigation"><span class="admin-nav-label">Workspace</span><a class="admin-nav-link" href="index.php"><span>⌂</span>Overview</a><a class="admin-nav-link" href="analytics.php"><span>⌁</span>Analytics</a><span class="admin-nav-label">Content</span><a class="admin-nav-link" href="media.php"><span>♫</span>Add Music</a><a class="admin-nav-link" href="videos.php"><span>▶</span>Add Video</a><a class="admin-nav-link active" href="playlists.php"><span>☷</span>Playlists</a><a class="admin-nav-link" href="reviews.php"><span>☆</span>Reviews</a><span class="admin-nav-label">Platform</span><a class="admin-nav-link" href="user-uploads.php"><span>◎</span>User Monitoring</a><a class="admin-nav-link" href="users.php"><span>◉</span>Users</a><a class="admin-nav-link" href="settings.php"><span>⚙</span>Website &amp; Catalog</a></nav>
<div class="admin-sidebar-bottom"><div class="admin-user-mini"><span class="admin-avatar"><?= htmlspecialchars(strtoupper(substr($user['name'],0,1)),ENT_QUOTES,'UTF-8') ?></span><div><strong><?= htmlspecialchars($user['name'],ENT_QUOTES,'UTF-8') ?></strong><small>Administrator</small></div></div><button class="admin-logout-btn" id="admin-logout">Log out <span>↗</span></button></div></aside>
<div class="admin-main-wrap"><header class="admin-topbar"><div class="admin-topbar-left"><button class="admin-icon-btn admin-mobile-menu" id="admin-sidebar-open" aria-label="Open navigation">☰</button><div><span class="eyebrow">CONTENT CONTROL</span><h2>Playlist Management</h2></div></div><div class="admin-topbar-actions"><button class="admin-btn admin-btn-ghost" id="playlist-refresh">Refresh <span>↻</span></button><a class="admin-btn admin-btn-ghost" href="../public/">View site <span>↗</span></a></div></header>
<main class="admin-main"><section class="admin-welcome"><div><span class="eyebrow">PHASE 6</span><h1>Monitor user playlists.</h1><p>Review playlist ownership, size and activity without changing personal media ownership.</p></div><div class="admin-live-status"><i></i><span>Admin access</span><small id="playlist-last-updated">Loading…</small></div></section>
<section class="admin-stat-grid" style="grid-template-columns:repeat(3,minmax(0,1fr))"><article class="admin-stat-card glass-card"><span>Playlists</span><strong id="playlist-stat-total">—</strong><small>Total playlists</small></article><article class="admin-stat-card glass-card"><span>Owners</span><strong id="playlist-stat-owners">—</strong><small>Users with playlists</small></article><article class="admin-stat-card glass-card"><span>Items</span><strong id="playlist-stat-items">—</strong><small>Total track links</small></article></section>
<section class="admin-panel glass-card"><div class="admin-panel-head"><div><span class="eyebrow">PLAYLIST LIBRARY</span><h2>All user playlists</h2></div><span class="admin-panel-meta" id="playlist-summary">Loading…</span></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Playlist</th><th>Created by</th><th>Email</th><th>Items</th><th>Created</th><th>Updated</th><th>Actions</th></tr></thead><tbody id="playlist-table-body"><tr><td colspan="7" class="admin-empty">Loading playlists…</td></tr></tbody></table></div></section>
</main></div></div><div class="admin-toast" id="admin-toast" role="status" aria-live="polite"></div><script src="assets/admin-playlists.js" defer></script></body></html>